name: JumpAndRun
version: '1.0-SNAPSHOT'
main: de.zettos.jumpandrun.JumpAndRun
author: Zettos
description: A Jump and Run Plugin
commands:
  area:
    usage: /<command>
    description: Set the Area for the Jump and Run
    permission: jumpandrun.area
